url: http://garbee.github.io/docs/
conurl: http://garbee.github.io/docs/contributor/
userurl: http://garbee.github.io/docs/user/
devurl: http://garbee.github.io/docs/developer/
jsurl: http://garbee.github.io/docs/assets/scripts/
cssurl: http://garbee.github.io/docs/assets/styles/
imageurl: http://garbee.github.io/docs/assets/images/
