url: http://phproad.github.io/docs/
conurl: http://phproad.github.io/docs/contributor/
userurl: http://phproad.github.io/docs/user/
devurl: http://phproad.github.io/docs/developer/
jsurl: http://phproad.github.io/docs/assets/scripts/
cssurl: http://phproad.github.io/docs/assets/styles/
imageurl: http://phproad.github.io/docs/assets/images/
